#!/bin/sh

checkError()
{
    if [ "${1}" -ne "0" ]; then
        echo "*** Error: ${2}"
        exit ${1}
    fi
}

cleanUp()
{
	if [ "$MIRAI_CLEAN_UP" == "yes" ]; then
		#clean up
		rm -rf libffi
	fi
}

if [ ! -f $MIRAI_SDK_PREFIX/lib/libffi.a ]; then
    echo "Building libffi"

    if [ ! -d libffi ]; then
        git clone https://github.com/atgreen/libffi.git
		
	    cp $GNUSTEP_MAKE_CONFIG_PATH/config.sub libffi
	    cp $GNUSTEP_MAKE_CONFIG_PATH/config.guess libffi
		
		pushd libffi
		
		git checkout 6ba2a49e226b859ddde9a37c34973cf85380c525
		
	    patch -p1 -i ../libffi_closures.patch

	    patch -p0 -i ../libffi-include-Makefile_am.patch
		
	    ./autogen.sh
		
		popd
    fi


    pushd libffi


    CC="$CROSS_CLANG" CXX="$CROSS_CLANGPP" CPPFLAGS="$ARCHFLAGS $SYSROOTFLAGS" CFLAGS="$ARCHFLAGS $SYSROOTFLAGS" ./configure --prefix=$MIRAI_SDK_PREFIX --host="$HOSTEABI" --with-sysroot=$MIRAI_SDK_PATH --disable-shared

    checkError $? "configure libffi failed"

    make install
    checkError $? "Make install libffi failed"
	
	popd
fi

cleanUp
