#!/bin/sh

checkError()
{
    if [ "${1}" -ne "0" ]; then
        echo "*** Error: ${2}"
        exit ${1}
    fi
}

cleanUp()
{
	if [ "$MIRAI_CLEAN_UP" == "yes" ]; then
		#clean up
		rm -f libxml2-2.9.0.tar.gz
		rm -rf libxml2-2.9.0
	fi
}

if [ ! -f $STANDALONE_TOOLCHAIN_PATH/sysroot/usr/lib/libxml2.a ]; then
    echo "Building libxml2"

	if [ ! -d libxml2-2.9.0 ]; then
	    if [ ! -f libxml2-2.9.0.tar.gz ]; then
	        curl -O ftp://xmlsoft.org/libxml2/libxml2-2.9.0.tar.gz
	    fi
		
	    tar -xzf libxml2-2.9.0.tar.gz
		
	    pushd libxml2-2.9.0
	    # remove tests that needs glob.h
	    patch -p1 -i ../libxml2_tests.patch
		popd
	fi

	pushd libxml2-2.9.0


    # build with gcc instead of clang
    # using clang produce an error missing symbol 'nan'
	CC="$CROSS_GCC"  CXX="$CROSS_CLANGPP" CPPFLAGS="$ARCHFLAGS $SYSROOTFLAGS" CFLAGS="$ARCHFLAGS $SYSROOTFLAGS" ./configure --prefix=$MIRAI_SDK_PREFIX --host="$HOSTEABI" --with-sysroot=$MIRAI_SDK_PATH --disable-shared
    checkError $? "configure libxml2 failed"
	
	make -j4
    checkError $? "Make libxml2 failed"
	
    make install
    checkError $? "Make install libxml2 failed"
	popd
	
fi

cleanUp