#!/bin/bash

foundFileList="no"
fileListPath=""
finalCommand=""
foundFramework="no"

for arg in "$@"
do
	newArg=$arg
	
    if [[ "$foundFileList" == "yes" && "$fileListPath" == "" ]]; then
        fileListPath="$arg"
		fileList=`sed ':a;N;$!ba;s/\n/ /g' "$fileListPath"`
		newArg="$fileList"
    fi
    if [ "$arg" == "-filelist" ]; then
        foundFileList="yes"
		continue;
    fi
	
	if [[ "$foundFramework" == "yes" ]]; then
		foundFramework="no"
		newArg="-l$arg"
	fi
	
    if [ "$arg" == "-framework" ]; then
        foundFramework="yes"
		continue;
    fi
	
	finalCommand="$finalCommand $newArg"
done

finalCommand=${finalCommand//" -dynamiclib "/" -shared "}

echo "final command: $finalCommand"
`dirname $0`/realld $finalCommand




