#!/bin/sh

pushd `pwd`/`dirname $0`
SCRIPT_ROOT=`pwd`
popd

checkError()
{
    if [ "${1}" -ne "0" ]; then
        echo "*** Error: ${2}"
        exit ${1}
    fi
}

cleanUp()
{
	if [ "$MIRAI_CLEAN_UP" == "yes" ]; then
		#clean up
		rm -rf libobjc2	
	fi
}

if [ ! -f $MIRAI_SDK_PREFIX/lib/libobjc.so ]; then

	if [ ! -d libobjc2 ]; then
		git clone https://github.com/MiraiSDK/libobjc2.git
		pushd libobjc2
		git checkout 02488ed8bcfc6612796d69b52b9a57c5c0b45f61
		popd
	fi

	mkdir -p libobjc2/Build
	pushd libobjc2/Build
	#clean
	rm -rf ./*

	# disable test, some tests failed due to cross-compiled 
	CFLAGS="$ARCHFLAGS" CXXFLAGS="$ARCHFLAGS" LDFLAGS="$ARCHLDFLAGS" \
	cmake -DCMAKE_BUILD_TYPE=Release \
		  -DTESTS=0 \
		  -DCMAKE_TOOLCHAIN_FILE=$SCRIPT_ROOT/toolchain-$ABI.cmake \
		  -DCMAKE_FIND_ROOT_PATH=$MIRAI_SDK_PATH \
		  -DCMAKE_INSTALL_PREFIX=/usr \
		  -DENABLE_SOVERSION=0 \
		  -DCXX_RUNTIME_NAME=libgnustl_shared.so ..
	make -j4
	checkError $? "build objc2 failed"
	
	make install DESTDIR=$STANDALONE_TOOLCHAIN_PATH/sysroot
	checkError $? "make install objc2 failed"
	
	popd
	
fi

cleanUp
