#!/bin/sh

pushd `pwd`/`dirname $0`
SCRIPT_ROOT=`pwd`
popd

checkError()
{
    if [ "${1}" -ne "0" ]; then
        echo "*** Error: ${2}"
        exit ${1}
    fi
}

cleanUp()
{
	if [ "$MIRAI_CLEAN_UP" == "yes" ]; then
		#clean up
		rm -rf libobjc2	
	fi
}

if [ ! -f $MIRAI_SDK_PREFIX/lib/libobjc.so ]; then

	if [ ! -d libobjc2 ]; then
		svn co http://svn.gna.org/svn/gnustep/libs/libobjc2/trunk libobjc2

		pushd libobjc2

		# apply patches
		patch -p0 -i ../libobjc2_SONAME.patch
		patch -p0 -i ../libobjc_android_test.diff
		popd
	fi

	mkdir -p libobjc2/Build
	pushd libobjc2/Build
	#clean
	rm -rf ./*

	# disable test, some tests failed due to cross-compiled 
	CFLAGS="$ARCHFLAGS" CXXFLAGS="$ARCHFLAGS" LDFLAGS="$ARCHLDFLAGS" cmake -DTESTS=0 -DCMAKE_TOOLCHAIN_FILE=$SCRIPT_ROOT/toolchain-$ABI.cmake -DCMAKE_FIND_ROOT_PATH=$MIRAI_SDK_PATH -DCMAKE_INSTALL_PREFIX=/usr ..
	make
	checkError $? "build objc2 failed"
	
	make install DESTDIR=$STANDALONE_TOOLCHAIN_PATH/sysroot
	checkError $? "make install objc2 failed"
	
	popd
	
fi

cleanUp
